on:
  push

name: Docker image vulnerability scan

jobs:
  anchore:
    name: Docker image vulnerability scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Docker image
      id: build-image
      env:
        IMAGE_NAME: ${{ github.repository }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        echo "image=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Scan Docker image
      uses: anchore/scan-action@main
      id: anchore-scan
      with:
        image: "${{ github.repository }}:${{ github.sha }}"
        severity-cutoff: critical
        fail-build: true
